In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [11]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))


In [15]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [17]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 10 ==0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)
print("Your score will be", sess.run(hypothesis, feed_dict={X:[100,70,101]})
)
print("Other scores will be", sess.run(hypothesis, feed_dict={X:[[60,70,110], [90,100,80]]}))

0 Cost: 9.359162 
Prediction:
 [[153.06223]
 [183.63522]
 [180.968  ]
 [199.38379]
 [137.9711 ]
 [105.02017]
 [152.5964 ]
 [117.86754]
 [174.24225]
 [166.2976 ]
 [144.55855]
 [143.20583]
 [184.66011]
 [150.1662 ]
 [153.48537]
 [188.54279]
 [140.11853]
 [184.75195]
 [175.7319 ]
 [157.6433 ]
 [178.16348]
 [174.47414]
 [169.23563]
 [148.94835]
 [189.33646]]
10 Cost: 9.338249 
Prediction:
 [[153.06384 ]
 [183.63693 ]
 [180.97006 ]
 [199.38275 ]
 [137.97505 ]
 [105.017975]
 [152.59082 ]
 [117.85669 ]
 [174.23976 ]
 [166.28804 ]
 [144.55647 ]
 [143.2024  ]
 [184.6656  ]
 [150.17546 ]
 [153.47937 ]
 [188.5414  ]
 [140.13127 ]
 [184.74326 ]
 [175.73773 ]
 [157.64792 ]
 [178.15808 ]
 [174.47253 ]
 [169.23143 ]
 [148.9578  ]
 [189.33981 ]]
20 Cost: 9.3175 
Prediction:
 [[153.06548 ]
 [183.63866 ]
 [180.97217 ]
 [199.38177 ]
 [137.97899 ]
 [105.01579 ]
 [152.58528 ]
 [117.845856]
 [174.23732 ]
 [166.27852 ]
 [144.55441 ]
 [143.19902 ]
 [184.67113 ]
 [150.18471 ]
 [153.4734  ]
 [188.54005 ]
 [140.

400 Cost: 8.624284 
Prediction:
 [[153.11806 ]
 [183.70314 ]
 [181.04457 ]
 [199.34526 ]
 [138.12352 ]
 [104.944084]
 [152.38567 ]
 [117.45706 ]
 [174.1567  ]
 [165.94862 ]
 [144.481   ]
 [143.08282 ]
 [184.86452 ]
 [150.51091 ]
 [153.26024 ]
 [188.49524 ]
 [140.59528 ]
 [184.4219  ]
 [175.94606 ]
 [157.81258 ]
 [177.96002 ]
 [174.41849 ]
 [169.07637 ]
 [149.29512 ]
 [189.46443 ]]
410 Cost: 8.608327 
Prediction:
 [[153.11923]
 [183.70482]
 [181.04633]
 [199.34435]
 [138.12718]
 [104.94246]
 [152.3807 ]
 [117.44739]
 [174.15488]
 [165.94073]
 [144.4792 ]
 [143.08008]
 [184.86922]
 [150.51888]
 [153.25499]
 [188.49423]
 [140.60638]
 [184.41412]
 [175.95096]
 [157.8164 ]
 [177.95526]
 [174.4173 ]
 [169.0726 ]
 [149.30304]
 [189.46747]]
420 Cost: 8.592464 
Prediction:
 [[153.12038 ]
 [183.70648 ]
 [181.04807 ]
 [199.34341 ]
 [138.13086 ]
 [104.94086 ]
 [152.37575 ]
 [117.437744]
 [174.15308 ]
 [165.93288 ]
 [144.47739 ]
 [143.07736 ]
 [184.8739  ]
 [150.52681 ]
 [153.24976 ]
 [188.49323 ]


830 Cost: 8.025097 
Prediction:
 [[153.15944 ]
 [183.77412 ]
 [181.11285 ]
 [199.30756 ]
 [138.27522 ]
 [104.885056]
 [152.18443 ]
 [117.06548 ]
 [174.0908  ]
 [165.64145 ]
 [144.40858 ]
 [142.97769 ]
 [185.05061 ]
 [150.82765 ]
 [153.04883 ]
 [188.45834 ]
 [141.03978 ]
 [184.10478 ]
 [176.13805 ]
 [157.9616  ]
 [177.76717 ]
 [174.37405 ]
 [168.92268 ]
 [149.60461 ]
 [189.58775 ]]
840 Cost: 8.013074 
Prediction:
 [[153.16022]
 [183.77576]
 [181.1143 ]
 [199.30673]
 [138.27861]
 [104.88393]
 [152.18005]
 [117.05694]
 [174.08955]
 [165.63506]
 [144.40704]
 [142.97554]
 [185.0546 ]
 [150.83444]
 [153.04427]
 [188.45766]
 [141.04938]
 [184.09784]
 [176.14212]
 [157.96472]
 [177.76297]
 [174.3732 ]
 [168.91931]
 [149.61113]
 [189.59048]]
850 Cost: 8.001146 
Prediction:
 [[153.16095]
 [183.77734]
 [181.1157 ]
 [199.3059 ]
 [138.28197]
 [104.8828 ]
 [152.17566]
 [117.04841]
 [174.08829]
 [165.62866]
 [144.40546]
 [142.97339]
 [185.05852]
 [150.84117]
 [153.03969]
 [188.45694]
 [141.0589 ]
 [1

1070 Cost: 7.757083 
Prediction:
 [[153.17572 ]
 [183.81258 ]
 [181.14558 ]
 [199.28809 ]
 [138.35463 ]
 [104.860504]
 [152.08235 ]
 [116.86699 ]
 [174.06363 ]
 [165.49594 ]
 [144.37251 ]
 [142.92924 ]
 [185.14145 ]
 [150.98346 ]
 [152.94298 ]
 [188.44301 ]
 [141.26103 ]
 [183.94313 ]
 [176.23051 ]
 [158.03221 ]
 [177.66988 ]
 [174.35497 ]
 [168.84407 ]
 [149.75307 ]
 [189.65077 ]]
1080 Cost: 7.7467933 
Prediction:
 [[153.17628]
 [183.81413]
 [181.14685]
 [199.28728]
 [138.35783]
 [104.85958]
 [152.07823]
 [116.85899]
 [174.0626 ]
 [165.49022]
 [144.37106]
 [142.92734]
 [185.14503]
 [150.98962]
 [152.93872]
 [188.44241]
 [141.26985]
 [183.9366 ]
 [176.23415]
 [158.03494]
 [177.66595]
 [174.35423]
 [168.84088]
 [149.7589 ]
 [189.6533 ]]
1090 Cost: 7.7365656 
Prediction:
 [[153.17688 ]
 [183.81573 ]
 [181.14816 ]
 [199.2865  ]
 [138.36108 ]
 [104.858696]
 [152.07416 ]
 [116.85105 ]
 [174.06165 ]
 [165.48456 ]
 [144.36963 ]
 [142.92549 ]
 [185.14862 ]
 [150.99582 ]
 [152.93452 ]
 [188.441

1310 Cost: 7.5274143 
Prediction:
 [[153.18791 ]
 [183.85005 ]
 [181.17493 ]
 [199.26962 ]
 [138.43037 ]
 [104.840996]
 [151.98695 ]
 [116.68159 ]
 [174.0422  ]
 [165.36652 ]
 [144.33922 ]
 [142.88704 ]
 [185.22401 ]
 [151.1259  ]
 [152.84496 ]
 [188.43079 ]
 [141.46507 ]
 [183.79155 ]
 [176.31374 ]
 [158.09499 ]
 [177.57932 ]
 [174.3393  ]
 [168.77019 ]
 [149.88632 ]
 [189.70993 ]]
1320 Cost: 7.5185814 
Prediction:
 [[153.18834 ]
 [183.8516  ]
 [181.1761  ]
 [199.26888 ]
 [138.43346 ]
 [104.84028 ]
 [151.98312 ]
 [116.674126]
 [174.04144 ]
 [165.36147 ]
 [144.33789 ]
 [142.88542 ]
 [185.2273  ]
 [151.13156 ]
 [152.84103 ]
 [188.43034 ]
 [141.47324 ]
 [183.78545 ]
 [176.31702 ]
 [158.09744 ]
 [177.5757  ]
 [174.33871 ]
 [168.76721 ]
 [149.89157 ]
 [189.71233 ]]
1330 Cost: 7.5098076 
Prediction:
 [[153.18877 ]
 [183.85313 ]
 [181.17725 ]
 [199.26813 ]
 [138.43654 ]
 [104.83958 ]
 [151.97931 ]
 [116.666695]
 [174.04068 ]
 [165.35643 ]
 [144.33655 ]
 [142.8838  ]
 [185.23055 ]
 [151.1372 

1540 Cost: 7.337821 
Prediction:
 [[153.19629 ]
 [183.88498 ]
 [181.20023 ]
 [199.25287 ]
 [138.49966 ]
 [104.826416]
 [151.90137 ]
 [116.515335]
 [174.02641 ]
 [165.25604 ]
 [144.30968 ]
 [142.85187 ]
 [185.29613 ]
 [151.25102 ]
 [152.75778 ]
 [188.42166 ]
 [141.64581 ]
 [183.65514 ]
 [176.38571 ]
 [158.14859 ]
 [177.49838 ]
 [174.32712 ]
 [168.70355 ]
 [150.0012  ]
 [189.76324 ]]
1550 Cost: 7.3301787 
Prediction:
 [[153.19658 ]
 [183.88649 ]
 [181.20126 ]
 [199.25215 ]
 [138.50261 ]
 [104.82586 ]
 [151.89778 ]
 [116.508354]
 [174.02582 ]
 [165.25151 ]
 [144.30844 ]
 [142.85043 ]
 [185.29912 ]
 [151.25621 ]
 [152.75414 ]
 [188.42131 ]
 [141.65337 ]
 [183.6494  ]
 [176.38869 ]
 [158.15079 ]
 [177.495   ]
 [174.32664 ]
 [168.70074 ]
 [150.00594 ]
 [189.76549 ]]
1560 Cost: 7.3225904 
Prediction:
 [[153.19687 ]
 [183.88797 ]
 [181.20229 ]
 [199.25145 ]
 [138.50554 ]
 [104.825325]
 [151.89418 ]
 [116.50138 ]
 [174.02522 ]
 [165.247   ]
 [144.3072  ]
 [142.84901 ]
 [185.30208 ]
 [151.2614  

1780 Cost: 7.167068 
Prediction:
 [[153.20204]
 [183.92038]
 [181.22394]
 [199.23633]
 [138.56863]
 [104.81495]
 [151.81776]
 [116.35298]
 [174.01418]
 [165.15338]
 [144.28116]
 [142.81998]
 [185.36475]
 [151.37076]
 [152.67332]
 [188.41446]
 [141.82024]
 [183.52147]
 [176.45349]
 [158.1984 ]
 [177.4196 ]
 [174.317  ]
 [168.63812]
 [150.10905]
 [189.81557]]
1790 Cost: 7.16049 
Prediction:
 [[153.20222 ]
 [183.92183 ]
 [181.22487 ]
 [199.23564 ]
 [138.57143 ]
 [104.814545]
 [151.81439 ]
 [116.34644 ]
 [174.01375 ]
 [165.14937 ]
 [144.28001 ]
 [142.81874 ]
 [185.36746 ]
 [151.37552 ]
 [152.66994 ]
 [188.4142  ]
 [141.8272  ]
 [183.51607 ]
 [176.45616 ]
 [158.20035 ]
 [177.41643 ]
 [174.31662 ]
 [168.63548 ]
 [150.1133  ]
 [189.81767 ]]
1800 Cost: 7.153949 
Prediction:
 [[153.20238 ]
 [183.92326 ]
 [181.22578 ]
 [199.23497 ]
 [138.5742  ]
 [104.81414 ]
 [151.81104 ]
 [116.339935]
 [174.01332 ]
 [165.14536 ]
 [144.27887 ]
 [142.8175  ]
 [185.37016 ]
 [151.38025 ]
 [152.66655 ]
 [188.41396 

ValueError: Cannot feed value of shape (3,) for Tensor 'Placeholder_2:0', which has shape '(?, 3)'